[profile.default]
src = "src"
out = "out"
libs = ['node_modules', 'lib']
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200

# auto_detect_remappings = true
remappings = [
    "@chainlink/contracts-ccip/=lib/ccip/contracts/",
    "@chainlink/local/src/v0.8/=node_modules/@chainlink/local/src/v0.8/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/"
]

fs_permissions = [{ access = "read-write", path = "./" }]

# evm_version = "shanghai"
evm_version = "paris"
#solc = '0.8.28'

[rpc_endpoints]
# ethSepolia = "${ETHEREUM_RPC_URL}"
# baseSepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
ethSepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111, url = "https://api-sepolia.etherscan.io/api" }

baseSepolia = { key = "${BASESCAN_API_KEY}", chain = 84532, url = "https://sepolia.base.org" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
